# Generated by Django 3.2.1 on 2022-05-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20220529_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.location'),
        ),
    ]
